name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      BOT_NAME: github-actions[bot]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create comment - Test Started
        uses: actions/github-script@v7
        id: pr-validation-start
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |

            const { BOT_NAME } = process.env;
            const prNumber = context.issue.number;
            const { owner, repo } = context.repo;

            const { data: comments } = await github.rest.pulls.listReviewComments({
              owner,
              repo,
              pull_number: prNumber,
            });

            console.log({comments});

            const botComments = comments.filter(comment => comment.user.login === BOT_NAME).shift();

            let commentId = botComments ? botComments.id : null;

            if(commentId){
                github.rest.issues.updateComment({
                    owner,
                    repo,
                    comment_id: commentId,
                    body: 'Workflow started'
                });
            } else {
                github.rest.issues.createComment({
                    owner,
                    repo,
                    issue_number: prNumber,
                    body: 'Workflow started'
                }); 
            }

      - name: Run tests
        run: |
          npm test
          # test runs too short. Give about 10 seconds till it ends
          sleep 10

      - name: Notify Test Result
        uses: actions/github-script@v7
        env:
          COMMENT_ID: ${{ steps.pr-validation-start.outputs.commentId }}
        with:
          script: |
            const { COMMENT_ID: commentId } = process.env
            const prNumber = context.issue.number;
            const { owner, repo } = context.repo;

            github.rest.issues.updateComment({
                owner,
                repo,
                comment_id: commentId,
                body: 'Tests ended successfully'
            });
